// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetFinancesResponse, CreateFinanceData, CreateFinanceResponse, GetFinanceData, GetFinanceResponse, UpdateFinanceData, UpdateFinanceResponse, DeleteFinanceData, DeleteFinanceResponse, GetFinancesByTypeData, GetFinancesByTypeResponse, GetFinancesByCategoryData, GetFinancesByCategoryResponse } from './types.gen';

export class Finances {
    /**
     * Get Finances
     * @returns FinanceSchema OK
     * @throws ApiError
     */
    public static getFinances(): CancelablePromise<GetFinancesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/finances'
        });
    }
    
    /**
     * Create Finance
     * @param data The data for the request.
     * @param data.requestBody
     * @returns FinanceSchema OK
     * @throws ApiError
     */
    public static createFinance(data: CreateFinanceData): CancelablePromise<CreateFinanceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/finances',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Get Finance
     * @param data The data for the request.
     * @param data.financeId
     * @returns DetailFinanceSchema OK
     * @throws ApiError
     */
    public static getFinance(data: GetFinanceData): CancelablePromise<GetFinanceResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/finances/{finance_id}',
            path: {
                finance_id: data.financeId
            }
        });
    }
    
    /**
     * Update Finance
     * @param data The data for the request.
     * @param data.financeId
     * @param data.requestBody
     * @returns FinanceSchema OK
     * @throws ApiError
     */
    public static updateFinance(data: UpdateFinanceData): CancelablePromise<UpdateFinanceResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/finances/{finance_id}',
            path: {
                finance_id: data.financeId
            },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
    /**
     * Delete Finance
     * @param data The data for the request.
     * @param data.financeId
     * @returns void No Content
     * @throws ApiError
     */
    public static deleteFinance(data: DeleteFinanceData): CancelablePromise<DeleteFinanceResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/finances/{finance_id}',
            path: {
                finance_id: data.financeId
            }
        });
    }
    
    /**
     * Get Finances By Type
     * @param data The data for the request.
     * @param data.financeType
     * @returns FinanceSchema OK
     * @throws ApiError
     */
    public static getFinancesByType(data: GetFinancesByTypeData): CancelablePromise<GetFinancesByTypeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/finances/type/{finance_type}',
            path: {
                finance_type: data.financeType
            }
        });
    }
    
    /**
     * Get Finances By Category
     * @param data The data for the request.
     * @param data.category
     * @returns FinanceSchema OK
     * @throws ApiError
     */
    public static getFinancesByCategory(data: GetFinancesByCategoryData): CancelablePromise<GetFinancesByCategoryResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/finances/category/{category}',
            path: {
                category: data.category
            }
        });
    }
}