// This file is auto-generated by @hey-api/openapi-ts

export type CreateFinanceSchema = {
    title: string;
    value: number;
    payment_date?: (string | null);
    due_date?: (string | null);
    category: string;
    type?: (FinanceType);
    status?: (FinanceStatus);
};

export type CreateFinanceSchemaPatch = {
    title?: (string | null);
    value?: (number | null);
    payment_date?: (string | null);
    due_date?: (string | null);
    category?: (string | null);
    type?: (FinanceType | null);
    status?: (FinanceStatus | null);
};

export type CreateOrUpdateSpendingLimitSchema = {
    value: (number | null);
};

export type DetailFinanceSchema = {
    id: number;
    created_by: UserSchema;
    type: FinanceType;
    status: FinanceStatus;
    due_date: (string | null);
    payment_date: (string | null);
    created_at: string;
    updated_at: string;
    attachments?: Array<FinanceAttachmentSchema>;
    title: string;
    value: (number | string);
    category: string;
};

export type FinanceAttachmentSchema = {
    id: number;
    created_by: (UserSchema | null);
    uploaded_at: string;
    file_url: string;
    name?: (string | null);
    content_type?: (string | null);
    size?: (number | null);
};

export type FinanceSchema = {
    id: number;
    created_by: UserSchema;
    type: FinanceType;
    status: FinanceStatus;
    due_date: (string | null);
    payment_date: (string | null);
    created_at: string;
    updated_at: string;
    title: string;
    value: (number | string);
    category: string;
};

export type FinanceStatus = 'Pendente' | 'Pago' | 'Atrasada';

export const FinanceStatus = {
    PENDENTE: 'Pendente',
    PAGO: 'Pago',
    ATRASADA: 'Atrasada'
} as const;

export type FinanceType = 'Receita' | 'Despesa';

export const FinanceType = {
    RECEITA: 'Receita',
    DESPESA: 'Despesa'
} as const;

export type SpendingLimitSchema = {
    id: number;
    user: UserSchema;
    value: (number | null);
    created_at: string;
    updated_at: string;
};

export type UserSchema = {
    id: string;
    name?: (string | null);
    email: string;
    image?: (string | null);
};

export type GetFinancesResponse = (Array<FinanceSchema>);

export type CreateFinanceData = {
    requestBody: CreateFinanceSchema;
};

export type CreateFinanceResponse = (FinanceSchema);

export type GetFinanceData = {
    financeId: number;
};

export type GetFinanceResponse = (DetailFinanceSchema);

export type UpdateFinanceData = {
    financeId: number;
    requestBody: CreateFinanceSchemaPatch;
};

export type UpdateFinanceResponse = (FinanceSchema);

export type DeleteFinanceData = {
    financeId: number;
};

export type DeleteFinanceResponse = (void);

export type UploadFinanceAttachmentsData = {
    financeId: number;
    formData: {
        files: Array<((Blob | File))>;
    };
};

export type UploadFinanceAttachmentsResponse = (Array<FinanceAttachmentSchema>);

export type DeleteFinanceAttachmentData = {
    attachmentId: number;
};

export type DeleteFinanceAttachmentResponse = (void);

export type GetSpendingLimitResponse = ((SpendingLimitSchema | null));

export type SetSpendingLimitData = {
    requestBody: CreateOrUpdateSpendingLimitSchema;
};

export type SetSpendingLimitResponse = (SpendingLimitSchema);

export type DeleteSpendingLimitResponse = (void);