// This file is auto-generated by @hey-api/openapi-ts

export type AddGoalRecordSchema = {
    title?: (string | null);
    value: number;
    type: string;
};

export type CreateFamilySchema = {
    name: string;
};

export type CreateFinanceSchema = {
    title: string;
    value: number;
    payment_date?: (string | null);
    due_date?: (string | null);
    category: string;
    type?: (FinanceType);
    status?: (FinanceStatus);
};

export type CreateFinanceSchemaPatch = {
    title?: (string | null);
    value?: (number | null);
    payment_date?: (string | null);
    due_date?: (string | null);
    category?: (string | null);
    type?: (FinanceType | null);
    status?: (FinanceStatus | null);
};

export type CreateGoalSchema = {
    title: string;
    target_value: number;
    deadline?: (string | null);
};

export type CreateOrUpdateSpendingLimitSchema = {
    value: (number | null);
};

export type DetailFinanceSchema = {
    id: number;
    created_by: UserSchema;
    type: FinanceType;
    status: FinanceStatus;
    due_date: (string | null);
    payment_date: (string | null);
    created_at: string;
    updated_at: string;
    attachments?: Array<FinanceAttachmentSchema>;
    family?: (number | null);
    title: string;
    value: (number | string);
    category: string;
};

export type FamilySchema = {
    id: number;
    name: string;
    code: string;
    created_by: UserSchema;
    created_at: string;
};

export type FinanceAttachmentSchema = {
    id: number;
    created_by: (UserSchema | null);
    uploaded_at: string;
    file_url: string;
    name?: (string | null);
    content_type?: (string | null);
    size?: (number | null);
};

export type FinanceSchema = {
    id: number;
    created_by: UserSchema;
    type: FinanceType;
    status: FinanceStatus;
    due_date: (string | null);
    payment_date: (string | null);
    created_at: string;
    updated_at: string;
    family?: (number | null);
    title: string;
    value: (number | string);
    category: string;
};

export type FinanceStatus = 'Pendente' | 'Pago' | 'Atrasada';

export const FinanceStatus = {
    PENDENTE: 'Pendente',
    PAGO: 'Pago',
    ATRASADA: 'Atrasada'
} as const;

export type FinanceType = 'Receita' | 'Despesa' | 'Meta';

export const FinanceType = {
    RECEITA: 'Receita',
    DESPESA: 'Despesa',
    META: 'Meta'
} as const;

export type GoalRecordSchema = {
    id: number;
    title: string;
    value: number;
    type: string;
    created_at: string;
};

export type GoalSchema = {
    id: number;
    title: string;
    target_value: number;
    current_value: number;
    progress: number;
    deadline: (string | null);
    created_at: string;
    updated_at: string;
    records: Array<GoalRecordSchema>;
};

export type JoinFamilySchema = {
    code: string;
};

export type SpendingLimitSchema = {
    id: number;
    user: UserSchema;
    value: (number | null);
    created_at: string;
    updated_at: string;
};

export type UploadProfilePhotoSchema = {
    photo_url: string;
};

export type UserSchema = {
    id: string;
    image?: (string | null);
    name?: (string | null);
    email: string;
};

export type GetFinancesResponse = (Array<FinanceSchema>);

export type CreateFinanceData = {
    goalId?: (number | null);
    requestBody: CreateFinanceSchema;
};

export type CreateFinanceResponse = (FinanceSchema);

export type GetFinanceData = {
    financeId: number;
};

export type GetFinanceResponse = (DetailFinanceSchema);

export type UpdateFinanceData = {
    financeId: number;
    requestBody: CreateFinanceSchemaPatch;
};

export type UpdateFinanceResponse = (FinanceSchema);

export type DeleteFinanceData = {
    financeId: number;
};

export type DeleteFinanceResponse = (void);

export type UploadFinanceAttachmentsData = {
    financeId: number;
    formData: {
        files: Array<((Blob | File))>;
    };
};

export type UploadFinanceAttachmentsResponse = (Array<FinanceAttachmentSchema>);

export type DeleteFinanceAttachmentData = {
    attachmentId: number;
};

export type DeleteFinanceAttachmentResponse = (void);

export type GetSpendingLimitResponse = ((SpendingLimitSchema | null));

export type SetSpendingLimitData = {
    requestBody: CreateOrUpdateSpendingLimitSchema;
};

export type SetSpendingLimitResponse = (SpendingLimitSchema);

export type DeleteSpendingLimitResponse = (void);

export type ListGoalsResponse = (Array<GoalSchema>);

export type CreateGoalData = {
    requestBody: CreateGoalSchema;
};

export type CreateGoalResponse = (GoalSchema);

export type GetGoalData = {
    goalId: number;
};

export type GetGoalResponse = (GoalSchema);

export type UpdateGoalData = {
    goalId: number;
    requestBody: CreateGoalSchema;
};

export type UpdateGoalResponse = (GoalSchema);

export type DeleteGoalData = {
    goalId: number;
};

export type DeleteGoalResponse = (void);

export type AddGoalRecordData = {
    goalId: number;
    requestBody: AddGoalRecordSchema;
};

export type AddGoalRecordResponse = (GoalSchema);

export type UploadProfilePhotoData = {
    formData: {
        file: (Blob | File);
    };
};

export type UploadProfilePhotoResponse = (UploadProfilePhotoSchema);

export type CreateFamilyData = {
    requestBody: CreateFamilySchema;
};

export type CreateFamilyResponse = (FamilySchema);

export type GetFamilyResponse = ((FamilySchema | null));

export type JoinFamilyData = {
    requestBody: JoinFamilySchema;
};

export type JoinFamilyResponse = (FamilySchema);

export type ListFamilyUsersResponse = (Array<UserSchema>);

export type LeaveFamilyResponse = (void);

export type RemoveFamilyMemberData = {
    userId: string;
};

export type RemoveFamilyMemberResponse = (void);