// This file is auto-generated by @hey-api/openapi-ts

export type CreateFinanceSchema = {
    title: string;
    description?: (string | null);
    value: number;
    payment_date?: (string | null);
    due_date?: (string | null);
    category: string;
    type?: (FinanceType);
    status?: (FinanceStatus);
};

export type CreateFinanceSchemaPatch = {
    title?: (string | null);
    description?: (string | null);
    value?: (number | null);
    payment_date?: (string | null);
    due_date?: (string | null);
    category?: (string | null);
    type?: (FinanceType | null);
    status?: (FinanceStatus | null);
};

export type CreateOrUpdateSpendingLimitSchema = {
    value: number;
};

export type DetailFinanceSchema = {
    id: number;
    created_by: UserSchema;
    type: FinanceType;
    status: FinanceStatus;
    due_date: (string | null);
    title: string;
    description?: (string | null);
    value: (number | string);
    payment_date?: (string | null);
    category: string;
    created_at: string;
    updated_at: string;
};

export type FinanceSchema = {
    id: number;
    created_by: UserSchema;
    type: FinanceType;
    status: FinanceStatus;
    due_date: (string | null);
    title: string;
    description?: (string | null);
    value: (number | string);
    payment_date?: (string | null);
    category: string;
    created_at: string;
    updated_at: string;
};

export type FinanceStatus = 'Pendente' | 'Pago' | 'Atrasada';

export const FinanceStatus = {
    PENDENTE: 'Pendente',
    PAGO: 'Pago',
    ATRASADA: 'Atrasada'
} as const;

export type FinanceType = 'Receita' | 'Despesa';

export const FinanceType = {
    RECEITA: 'Receita',
    DESPESA: 'Despesa'
} as const;

export type SpendingLimitSchema = {
    id?: (number | null);
    user: string;
    value?: (number | string);
    created_at: string;
    updated_at: string;
};

export type UserSchema = {
    id: string;
    name?: (string | null);
    email: string;
    image?: (string | null);
};

export type GetFinancesResponse = (Array<FinanceSchema>);

export type CreateFinanceData = {
    requestBody: CreateFinanceSchema;
};

export type CreateFinanceResponse = (FinanceSchema);

export type GetFinanceData = {
    financeId: number;
};

export type GetFinanceResponse = (DetailFinanceSchema);

export type UpdateFinanceData = {
    financeId: number;
    requestBody: CreateFinanceSchemaPatch;
};

export type UpdateFinanceResponse = (FinanceSchema);

export type DeleteFinanceData = {
    financeId: number;
};

export type DeleteFinanceResponse = (void);

export type GetFinancesByTypeData = {
    financeType: 'Receita' | 'Despesa';
};

export type GetFinancesByTypeResponse = (Array<FinanceSchema>);

export type GetFinancesByCategoryData = {
    category: string;
};

export type GetFinancesByCategoryResponse = (Array<FinanceSchema>);

export type GetSpendingLimitResponse = (SpendingLimitSchema);

export type SetSpendingLimitData = {
    requestBody: CreateOrUpdateSpendingLimitSchema;
};

export type SetSpendingLimitResponse = (SpendingLimitSchema);