# Generated by Django 5.2.5 on 2025-09-02 17:35

import app.types
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=45)),
                ('type', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], default=app.types.FinanceStatus['PENDING'], max_length=10)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'verbose_name': 'finance',
                'verbose_name_plural': 'finances',
                'db_table': 'finances',
                'ordering': ['-date', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Finances',
        ),
        migrations.AddIndex(
            model_name='finance',
            index=models.Index(fields=['type', 'category', 'deleted_at'], name='finances_type_ff232d_idx'),
        ),
        migrations.AddIndex(
            model_name='finance',
            index=models.Index(fields=['date', 'deleted_at'], name='finances_date_483a91_idx'),
        ),
    ]
