# Generated by Django 5.2.5 on 2025-09-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_finance_delete_finances_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='finance',
            name='finances_type_ff232d_idx',
        ),
        migrations.RemoveIndex(
            model_name='finance',
            name='finances_date_483a91_idx',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='deleted_at',
        ),
        migrations.AddIndex(
            model_name='finance',
            index=models.Index(fields=['type', 'category'], name='finances_type_d9b14e_idx'),
        ),
        migrations.AddIndex(
            model_name='finance',
            index=models.Index(fields=['date'], name='finances_date_08dd54_idx'),
        ),
    ]
