# Generated by Django 5.2.5 on 2025-09-09 15:14

import app.types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_finance_finances_type_ff232d_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={'ordering': ['-date', 'created_at']},
        ),
        migrations.RemoveIndex(
            model_name='finance',
            name='finances_type_d9b14e_idx',
        ),
        migrations.RemoveIndex(
            model_name='finance',
            name='finances_date_08dd54_idx',
        ),
        migrations.AddField(
            model_name='finance',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Atrasada', 'Atrasada')], default=app.types.FinanceStatus['PENDING'], max_length=15),
        ),
        migrations.AlterField(
            model_name='finance',
            name='type',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=10),
        ),
    ]
