# Generated by Django 5.2.5 on 2025-09-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_finance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={'ordering': ['-payment_date', 'created_at']},
        ),
        migrations.RenameField(
            model_name='finance',
            old_name='date',
            new_name='payment_date',
        ),
    ]
