# Generated by Django 5.2.5 on 2025-09-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_finance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
