# Generated by Django 5.2.5 on 2025-09-11 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_finance_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingLimit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spending_limit', to='app.user')),
            ],
            options={
                'db_table': 'spending_limits',
            },
        ),
    ]
