# Generated by Django 5.2.5 on 2025-09-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_spendinglimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='description',
        ),
    ]
