# Generated by Django 5.2.5 on 2025-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_finance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendinglimit',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
