# Generated by Django 5.2.5 on 2025-09-30 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_spendinglimit_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='financas')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.finance')),
            ],
            options={
                'db_table': 'finance_files',
            },
        ),
    ]
