# Generated by Django 5.2.5 on 2025-10-01 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_financefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='finances')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.finance')),
            ],
            options={
                'db_table': 'finance_attachments',
            },
        ),
        migrations.DeleteModel(
            name='FinanceFile',
        ),
    ]
