# Generated by Django 5.2.5 on 2025-10-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_financeattachment_delete_financefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='scope',
            field=models.TextField(null=True),
        ),
    ]
