# Generated by Django 5.2.5 on 2025-10-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_account_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='type',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa'), ('Meta', 'Meta')], max_length=10),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='app.user')),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Adicionar', 'Adicionar'), ('Retirar', 'Retirar')], max_length=10)),
                ('finance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.finance')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.goal')),
            ],
            options={
                'db_table': 'goal_records',
            },
        ),
    ]
