# Generated by Django 5.2.5 on 2025-10-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_finance_type_goal_goalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalrecord',
            name='finance',
        ),
    ]
