# Generated by Django 5.2.5 on 2025-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_goalrecord_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
